### ISSUE TITLE
App crash at launch

### ISSUE THREAD

**Issue by perqa** [WayneMorganUK/sveltekit-movie-app#1]
I am trying to launch the project by `npm run dev -- --open`. Building it works fine, but when launching the app in a browser, I get this error:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at Proxy.each (/Users/xxx/Workspace/sveltekit-movie-app/node_modules/svelte/internal/index.js:1649:31)
    at Genre.svelte:13:9
    at Object.$$render (/Users/xxx/Workspace/sveltekit-movie-app/node_modules/svelte/internal/index.js:1684:22)
    at eval (/src/lib/utilities/Selector.svelte:66:198)
    at Object.$$render (/Users/xxx/Workspace/sveltekit-movie-app/node_modules/svelte/internal/index.js:1684:22)
    at eval (/src/lib/components/Header.svelte:36:90)
    at Object.$$render (/Users/xxx/Workspace/sveltekit-movie-app/node_modules/svelte/internal/index.js:1684:22)
    at eval (/src/routes/__layout.svelte:62:171)
    at Object.$$render (/Users/xxx/Workspace/sveltekit-movie-app/node_modules/svelte/internal/index.js:1684:22)
    at root.svelte:36:44
```

Checking the undefined object at Genre.svelte:13:9, $movie_genres:

```
{@debug} /Users/xxx/Workspace/sveltekit-movie-app/src/lib/components/Genre.svelte (3:20)
{
  movie_genres: {
    set: [Function: set],
    update: [Function: update],
    subscribe: [Function: subscribe]
  }
}
```

- node --version v16.13.0
- npm --version v8.1.0
- MacOS v11.16

**Comment by WayneMorganUK** [comment]
An API key is required which is available from [TMDB](https://www.themoviedb.org/faq/api).
This needs to added to a `.env' file created in root folder for development or added to your hosts Environment Variables

**Comment by perqa** [comment]
Thanks @WayneMorganUK! Works as expected.
